### ISSUE TITLE
Dashboard unavailable after ESPHome version change

### ISSUE THREAD

**Issue by ilium007** [esphome/dashboard#22]
**Operating environment/Installation (Hass.io/Docker/pip/etc.):**

ESPHome in Docker behind SWAG (https://hub.docker.com/r/linuxserver/swag) reverse proxy.

docker-compose entry:

```
esphome:
    #image: esphome/esphome:1.18.0
    image: esphome/esphome:1.19.2
    container_name: esphome
    networks:
      - ha_network
    environment:
      - ESPHOME_DASHBOARD_USE_PING=true
    volumes:
        - /docker/esphome/config:/config
    ports:
      - 6052:6052
    restart: unless-stopped
```

**ESP (ESP32/ESP8266, Board/Sonoff):**

ESP32 / ESP8266
**ESPHome version (latest production, beta, dev branch)**

latest

**Affected component:**

**Description of problem:**

Upgraded Docker image from 1.18.0 to 1.19.0 then 1.19.1 and then 1.19.2. Each time I tried restarting the Docker container but the dashboard UI elements were unresponsive in Safari and Firefox but worked in Chrome. 

I have tried restarting browsers, clearing caches etc but the dashboard remains unresponsive.

All elements are grey, none of the usual link elements respond when clicked.

Safari:
<img width="452" alt="image" src="https://user-images.githubusercontent.com/732766/122875259-5d035300-d377-11eb-9076-f1284632d8a3.png">

Chrome:
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/732766/122875444-989e1d00-d377-11eb-91ae-c0c4d2596e6b.png">

If I roll back to 1.18.0 everything works in Safari again:
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/732766/122875673-e9157a80-d377-11eb-8250-aef7cc2f4c70.png">

**Problem-relevant YAML-configuration entries:**
```yaml
PASTE YAML FILE HERE

```

**Logs (if applicable):**

```
PASTE DEBUG LOG HERE

```

**Additional information and things you've tried:**
