### ISSUE TITLE
ESPHome always requires a WiFi network

### ISSUE THREAD

**Issue by ChillingSilence** [esphome/dashboard#532]
### The problem

When setting up ESPHome, even if the user _only_ ever uses something such as the M5Stack PoESP32, ESPHome still requires a WiFi network be entered on the first device.

While only a minor inconvenience of having to make up a non-existent WiFi network, there *may* still be a better way of handling this requirement. Perhaps some sort of "yeah naaaah this is LAN-only"?

![image](https://github.com/esphome/issues/assets/162461/846fc484-e390-4205-bbf7-35d3c18c7737)

The PoESP32 does not have any method of utilising the WiFi that is traditionally included in the ESP32.

### Which version of ESPHome has the issue?

2023.5.5

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2023.5.4

### What platform are you using?

ESP32

### Board

M5Stack PoESP32

### Component causing the issue

esphome

### Example YAML snippet

```yaml
esphome:
  name: m5stack-poesp32-25

esp32:
  board: m5stack-core-esp32
  framework:
    type: arduino

# Enable logging
logger:

# Keep this, coz you can't flash shit remotely without it
ota:

# Network interface for PoESP32
ethernet:
  type: IP101
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO5

# Enable Home Assistant API
api:
  encryption:
    key: "****"
```

### Anything in the logs that might be useful for us?

```txt
N/A
```

### Additional information

![Screenshot 2023-05-30 193520](https://github.com/esphome/issues/assets/162461/1b802d52-ca1e-452b-9d57-e9608ef94597)
